name: Basic Workflow

on: push
#on: workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
   
    steps:
      - name: Echo Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
            exit 1
    steps:
      - name: Failed Step
        run: echo "It will be success!"
             exit 1